using Crm.Domain.Common;

namespace Crm.Domain.Tickets;

[Audited]
public sealed class Ticket : AuditableEntity, ISoftDelete, IHasRowVersion
{
    public const int MaxEscalationLevel = 3;
    public const int SubjectMaxLength = 250;

    private static readonly Dictionary<TicketStatus, TicketStatus[]> Transitions = new()
    {
        [TicketStatus.New] = [TicketStatus.Open, TicketStatus.InProgress, TicketStatus.Closed],
        [TicketStatus.Open] = [TicketStatus.InProgress, TicketStatus.PendingCustomer, TicketStatus.Resolved, TicketStatus.Closed],
        [TicketStatus.InProgress] = [TicketStatus.Open, TicketStatus.PendingCustomer, TicketStatus.Resolved, TicketStatus.Closed],
        [TicketStatus.PendingCustomer] = [TicketStatus.Open, TicketStatus.InProgress, TicketStatus.Resolved, TicketStatus.Closed],
        [TicketStatus.Resolved] = [TicketStatus.Open, TicketStatus.Closed],
        [TicketStatus.Closed] = [TicketStatus.Open],
    };

    private readonly List<TicketHistoryEntry> _history = [];

    private Ticket() { }

    private Ticket(
        string subject, string description, Guid customerId, Guid? contactPersonId, Channel channel,
        Guid categoryId, TicketPriority priority, Guid departmentId, Guid? branchId, Guid? actorId, DateTimeOffset now)
    {
        SetSubject(subject);
        SetDescription(description);
        CustomerId = customerId;
        ContactPersonId = contactPersonId;
        Channel = channel;
        CategoryId = categoryId;
        Priority = priority;
        DepartmentId = departmentId;
        BranchId = branchId;
        Status = TicketStatus.New;
        CreatedAt = now;
        AddHistory(now, actorId, TicketChangeType.Created);
    }

    /// <summary>Generated by the database (<c>TCK-000001</c>).</summary>
    public string ReferenceNumber { get; private set; } = null!;
    public string Subject { get; private set; } = string.Empty;
    public string Description { get; private set; } = string.Empty;
    public Guid CustomerId { get; private set; }
    public Guid? ContactPersonId { get; private set; }
    public Channel Channel { get; private set; }
    public Guid CategoryId { get; private set; }
    public TicketPriority Priority { get; private set; }
    public TicketStatus Status { get; private set; }
    public Guid DepartmentId { get; private set; }
    public Guid? BranchId { get; private set; }
    public Guid? AssigneeId { get; private set; }
    public int EscalationLevel { get; private set; }
    public DateTimeOffset? FirstRespondedAt { get; private set; }
    public DateTimeOffset? ResolvedAt { get; private set; }
    public DateTimeOffset? ClosedAt { get; private set; }
    public bool IsDeleted { get; private set; }
    public byte[] RowVersion { get; private set; } = [];

    public IReadOnlyList<TicketHistoryEntry> History => _history.AsReadOnly();

    public static Ticket Create(
        string subject, string description, Guid customerId, Guid? contactPersonId, Channel channel,
        Guid categoryId, TicketPriority priority, Guid departmentId, Guid? branchId, Guid? actorId, DateTimeOffset now) =>
        new(subject, description, customerId, contactPersonId, channel, categoryId, priority, departmentId, branchId, actorId, now);

    public IReadOnlyList<TicketStatus> AllowedTransitions() => Transitions[Status];

    public void UpdateDetails(string subject, Guid categoryId, TicketPriority priority, Guid departmentId, Guid? actorId, DateTimeOffset now)
    {
        EnsureNotClosed();
        subject = subject.Trim();
        if (subject != Subject)
        {
            var old = Subject;
            SetSubject(subject);
            AddHistory(now, actorId, TicketChangeType.FieldChanged, nameof(Subject), old, Subject);
        }

        if (categoryId != CategoryId)
        {
            AddHistory(now, actorId, TicketChangeType.FieldChanged, nameof(CategoryId), CategoryId.ToString(), categoryId.ToString());
            CategoryId = categoryId;
        }

        if (priority != Priority)
        {
            AddHistory(now, actorId, TicketChangeType.FieldChanged, nameof(Priority), Priority.ToString(), priority.ToString());
            Priority = priority;
        }

        if (departmentId != DepartmentId)
        {
            AddHistory(now, actorId, TicketChangeType.FieldChanged, nameof(DepartmentId), DepartmentId.ToString(), departmentId.ToString());
            DepartmentId = departmentId;
        }
    }

    /// <summary>Assigns (or with <c>null</c>, returns to the queue). A new ticket becomes Open when assigned.</summary>
    public void Assign(Guid? assigneeId, Guid? actorId, DateTimeOffset now, string? reason = null)
    {
        EnsureNotClosed();
        if (assigneeId == AssigneeId)
        {
            return;
        }

        AddHistory(now, actorId, TicketChangeType.Assigned, nameof(AssigneeId), AssigneeId?.ToString(), assigneeId?.ToString(), reason);
        AssigneeId = assigneeId;
        if (assigneeId is not null && Status == TicketStatus.New)
        {
            ChangeStatusInternal(TicketStatus.Open, actorId, now, reason: null);
        }
    }

    /// <summary>An agent takes an unassigned ticket from the queue.</summary>
    public void Take(Guid agentId, DateTimeOffset now)
    {
        if (AssigneeId is not null)
        {
            throw new ConflictException("ticket.already-assigned", "This ticket is already assigned.");
        }

        Assign(agentId, agentId, now);
    }

    public void ChangeStatus(TicketStatus newStatus, Guid? actorId, DateTimeOffset now, string? reason = null)
    {
        if (newStatus == Status)
        {
            return;
        }

        if (!Transitions[Status].Contains(newStatus))
        {
            throw new ConflictException("ticket.invalid-transition", $"A ticket cannot move from {Status} to {newStatus}.");
        }

        if (newStatus == TicketStatus.Closed && Status != TicketStatus.Resolved && string.IsNullOrWhiteSpace(reason))
        {
            throw new DomainException("ticket.close-reason-required", "A reason is required to close a ticket that was not resolved.");
        }

        ChangeStatusInternal(newStatus, actorId, now, reason);
    }

    public void Escalate(string reason, Guid? escalationOwnerId, Guid? actorId, DateTimeOffset now)
    {
        EnsureNotClosed();
        if (string.IsNullOrWhiteSpace(reason))
        {
            throw new DomainException("ticket.escalation-reason-required", "A reason is required to escalate a ticket.");
        }

        if (EscalationLevel >= MaxEscalationLevel)
        {
            throw new ConflictException("ticket.max-escalation", "This ticket is already at the highest escalation level.");
        }

        EscalationLevel++;
        AddHistory(now, actorId, TicketChangeType.Escalated, nameof(EscalationLevel),
            (EscalationLevel - 1).ToString(System.Globalization.CultureInfo.InvariantCulture),
            EscalationLevel.ToString(System.Globalization.CultureInfo.InvariantCulture), reason.Trim());

        if (escalationOwnerId is not null)
        {
            Assign(escalationOwnerId, actorId, now, "Escalation");
        }
    }

    /// <summary>Called when an agent sends a public reply to the customer.</summary>
    public void RecordAgentReply(Guid actorId, DateTimeOffset now)
    {
        EnsureNotClosed();
        FirstRespondedAt ??= now;
        if (Status == TicketStatus.New)
        {
            ChangeStatusInternal(TicketStatus.Open, actorId, now, reason: null);
        }
    }

    /// <summary>
    /// Called when the customer replies. Returns <c>false</c> when the ticket was closed longer than
    /// <paramref name="reopenWindow"/> ago, in which case the caller must open a new ticket.
    /// </summary>
    public bool RecordCustomerReply(DateTimeOffset now, TimeSpan reopenWindow)
    {
        switch (Status)
        {
            case TicketStatus.Closed when ClosedAt is not null && now - ClosedAt.Value > reopenWindow:
                return false;
            case TicketStatus.Closed:
            case TicketStatus.Resolved:
                ChangeStatusInternal(TicketStatus.Open, actorId: null, now, "Customer replied");
                _history[^1] = _history[^1] with { ChangeType = TicketChangeType.Reopened };
                return true;
            case TicketStatus.PendingCustomer:
                ChangeStatusInternal(TicketStatus.Open, actorId: null, now, "Customer replied");
                return true;
            default:
                return true;
        }
    }

    public void MarkDeleted() => IsDeleted = true;

    private void ChangeStatusInternal(TicketStatus newStatus, Guid? actorId, DateTimeOffset now, string? reason)
    {
        AddHistory(now, actorId, TicketChangeType.StatusChanged, nameof(Status), Status.ToString(), newStatus.ToString(), reason);
        Status = newStatus;
        switch (newStatus)
        {
            case TicketStatus.Resolved:
                ResolvedAt = now;
                break;
            case TicketStatus.Closed:
                ClosedAt = now;
                break;
            case TicketStatus.Open or TicketStatus.InProgress:
                ResolvedAt = null;
                ClosedAt = null;
                break;
        }
    }

    private void EnsureNotClosed()
    {
        if (Status == TicketStatus.Closed)
        {
            throw new ConflictException("ticket.closed", "Closed tickets cannot be changed. Reopen the ticket first.");
        }
    }

    private void SetSubject(string subject)
    {
        if (string.IsNullOrWhiteSpace(subject))
        {
            throw new DomainException("ticket.subject-required", "Subject is required.");
        }

        if (subject.Length > SubjectMaxLength)
        {
            throw new DomainException("ticket.subject-too-long", $"Subject must be {SubjectMaxLength} characters or fewer.");
        }

        Subject = subject.Trim();
    }

    private void SetDescription(string description)
    {
        if (string.IsNullOrWhiteSpace(description))
        {
            throw new DomainException("ticket.description-required", "Description is required.");
        }

        Description = description.Trim();
    }

    private void AddHistory(
        DateTimeOffset now, Guid? actorId, TicketChangeType type,
        string? field = null, string? oldValue = null, string? newValue = null, string? reason = null) =>
        _history.Add(new TicketHistoryEntry(Id, now, actorId, type, field, oldValue, newValue, reason));
}
