using System.Text.RegularExpressions;
using Crm.Domain.Common;

namespace Crm.Domain.Customers;

[Audited]
public sealed partial class Customer : AuditableEntity, ISoftDelete, IHasRowVersion
{
    private readonly List<ContactPerson> _contacts = [];

    private Customer() { }

    public Customer(CustomerType type, string name, string? email, string? phone, Language preferredLanguage, Guid? branchId)
    {
        Type = type;
        PreferredLanguage = preferredLanguage;
        BranchId = branchId;
        UpdateDetails(name, email, phone);
    }

    /// <summary>Generated by the database (<c>CUS-000001</c>).</summary>
    public string ReferenceNumber { get; private set; } = null!;
    public CustomerType Type { get; private set; }
    public string Name { get; private set; } = string.Empty;
    public string? PrimaryEmail { get; private set; }
    public string? PrimaryPhone { get; private set; }
    public Address? Address { get; private set; }
    public Language PreferredLanguage { get; private set; }
    public Guid? BranchId { get; private set; }
    public string? ErpReference { get; private set; }
    public bool NeedsReview { get; private set; }
    public bool IsDeleted { get; private set; }
    public byte[] RowVersion { get; private set; } = [];

    public IReadOnlyCollection<ContactPerson> Contacts => _contacts.AsReadOnly();

    /// <summary>Creates a profile for an unknown sender; flagged so an agent can review or merge it.</summary>
    public static Customer CreateFromUnknownSender(string? name, string? email, string? phone, Language language)
    {
        var displayName = string.IsNullOrWhiteSpace(name) ? (email ?? phone ?? "Unknown") : name;
        return new Customer(CustomerType.Individual, displayName, email, phone, language, branchId: null)
        {
            NeedsReview = true,
        };
    }

    public void UpdateDetails(string name, string? email, string? phone)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            throw new DomainException("customer.name-required", "Customer name is required.");
        }

        email = Normalize(email)?.ToLowerInvariant();
        phone = Normalize(phone);

        if (email is null && phone is null)
        {
            throw new DomainException("customer.contact-required", "A customer needs an email address or a phone number.");
        }

        if (phone is not null && !E164().IsMatch(phone))
        {
            throw new DomainException("customer.phone-format", "Phone number must be in international format, e.g. +966501234567.");
        }

        Name = name.Trim();
        PrimaryEmail = email;
        PrimaryPhone = phone;
    }

    public void UpdateProfile(CustomerType type, Language preferredLanguage, Guid? branchId, Address? address, string? erpReference)
    {
        if (type == CustomerType.Individual && _contacts.Count > 0)
        {
            throw new DomainException("customer.type-has-contacts", "Remove contact persons before changing a company to an individual.");
        }

        Type = type;
        PreferredLanguage = preferredLanguage;
        BranchId = branchId;
        Address = address;
        ErpReference = Normalize(erpReference);
    }

    public void MarkReviewed() => NeedsReview = false;

    public ContactPerson AddContact(string name, string? email, string? phone, string? jobTitle, bool isPrimary)
    {
        if (Type != CustomerType.Company)
        {
            throw new DomainException("customer.contacts-company-only", "Only company customers can have contact persons.");
        }

        var contact = new ContactPerson(Id, name, email, phone, jobTitle);
        _contacts.Add(contact);
        if (isPrimary || _contacts.Count == 1)
        {
            SetPrimaryContact(contact.Id);
        }

        return contact;
    }

    public void UpdateContact(Guid contactId, string name, string? email, string? phone, string? jobTitle, bool isPrimary)
    {
        var contact = FindContact(contactId);
        contact.Update(name, email, phone, jobTitle);
        if (isPrimary)
        {
            SetPrimaryContact(contactId);
        }
    }

    public void RemoveContact(Guid contactId)
    {
        var contact = FindContact(contactId);
        _contacts.Remove(contact);
        if (contact.IsPrimary && _contacts.Count > 0)
        {
            SetPrimaryContact(_contacts[0].Id);
        }
    }

    public bool HasContact(Guid contactId) => _contacts.Exists(c => c.Id == contactId);

    public void MarkDeleted() => IsDeleted = true;

    private void SetPrimaryContact(Guid contactId)
    {
        foreach (var c in _contacts)
        {
            c.SetPrimary(c.Id == contactId);
        }
    }

    private ContactPerson FindContact(Guid contactId) =>
        _contacts.Find(c => c.Id == contactId)
        ?? throw new DomainException("customer.contact-not-found", "Contact person not found.");

    private static string? Normalize(string? value) => string.IsNullOrWhiteSpace(value) ? null : value.Trim();

    [GeneratedRegex(@"^\+[1-9][0-9]{6,14}$")]
    private static partial Regex E164();
}
